package gui;

import java.awt.Color;

/**
 *
 * @author Igor
 */
public class DialogHSB extends javax.swing.JDialog {
    
    /**
     * Creates new form DialogHSB
     * @param parent
     * @param modal
     */
    public DialogHSB(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonApply = new javax.swing.JButton();
        jPanelSaturation = new javax.swing.JPanel();
        jSliderSaturation = new javax.swing.JSlider();
        jPanelBrightness = new javax.swing.JPanel();
        jSliderBrightness = new javax.swing.JSlider();
        jPanelHue = new javax.swing.JPanel();
        jSliderHue = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HSB Filter");
        setResizable(false);

        jButtonApply.setText("Apply");
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });

        jPanelSaturation.setBorder(javax.swing.BorderFactory.createTitledBorder("Saturation"));

        jSliderSaturation.setMajorTickSpacing(50);
        jSliderSaturation.setMinimum(-100);
        jSliderSaturation.setMinorTickSpacing(10);
        jSliderSaturation.setPaintLabels(true);
        jSliderSaturation.setPaintTicks(true);
        jSliderSaturation.setToolTipText("");
        jSliderSaturation.setValue(0);
        jSliderSaturation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSliderSaturation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderSaturationMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelSaturationLayout = new javax.swing.GroupLayout(jPanelSaturation);
        jPanelSaturation.setLayout(jPanelSaturationLayout);
        jPanelSaturationLayout.setHorizontalGroup(
            jPanelSaturationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderSaturation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSaturationLayout.setVerticalGroup(
            jPanelSaturationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderSaturation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelBrightness.setBorder(javax.swing.BorderFactory.createTitledBorder("Brightness"));

        jSliderBrightness.setMajorTickSpacing(50);
        jSliderBrightness.setMinimum(-100);
        jSliderBrightness.setMinorTickSpacing(10);
        jSliderBrightness.setPaintLabels(true);
        jSliderBrightness.setPaintTicks(true);
        jSliderBrightness.setValue(0);
        jSliderBrightness.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSliderBrightness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderBrightnessMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelBrightnessLayout = new javax.swing.GroupLayout(jPanelBrightness);
        jPanelBrightness.setLayout(jPanelBrightnessLayout);
        jPanelBrightnessLayout.setHorizontalGroup(
            jPanelBrightnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderBrightness, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBrightnessLayout.setVerticalGroup(
            jPanelBrightnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderBrightness, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelHue.setBorder(javax.swing.BorderFactory.createTitledBorder("Hue"));

        jSliderHue.setMajorTickSpacing(60);
        jSliderHue.setMaximum(360);
        jSliderHue.setMinorTickSpacing(20);
        jSliderHue.setPaintLabels(true);
        jSliderHue.setPaintTicks(true);
        jSliderHue.setValue(180);
        jSliderHue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSliderHue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderHueMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelHueLayout = new javax.swing.GroupLayout(jPanelHue);
        jPanelHue.setLayout(jPanelHueLayout);
        jPanelHueLayout.setHorizontalGroup(
            jPanelHueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderHue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelHueLayout.setVerticalGroup(
            jPanelHueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderHue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSaturation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBrightness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jButtonApply, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelHue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSaturation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBrightness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonApply, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanelBrightness, jPanelHue, jPanelSaturation});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderHueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderHueMouseReleased
        //this.hue = jSliderHue.getValue();
        System.out.println("Hue set to " + jSliderHue.getValue());
        jSliderHue.setBackground(Color.getHSBColor((float) (jSliderHue.getValue()/360.), (float) 1, (float) 1));
    }//GEN-LAST:event_jSliderHueMouseReleased

    private void jSliderSaturationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderSaturationMouseReleased
         //this.saturation = jSliderSaturation.getValue();
         System.out.println("Saturation set to " + jSliderSaturation.getValue());
    }//GEN-LAST:event_jSliderSaturationMouseReleased

    private void jSliderBrightnessMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderBrightnessMouseReleased
         //this.brightness = jSliderBrightness.getValue();
         System.out.println("Brightness set to " + jSliderBrightness.getValue());
    }//GEN-LAST:event_jSliderBrightnessMouseReleased

    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonApplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogHSB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogHSB dialog = new DialogHSB(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApply;
    private javax.swing.JPanel jPanelBrightness;
    private javax.swing.JPanel jPanelHue;
    private javax.swing.JPanel jPanelSaturation;
    private javax.swing.JSlider jSliderBrightness;
    private javax.swing.JSlider jSliderHue;
    private javax.swing.JSlider jSliderSaturation;
    // End of variables declaration//GEN-END:variables

    public int getHue(){
        return jSliderHue.getValue();
    }
    
     public int getSaturation(){
        return jSliderSaturation.getValue();
    }
     
      public int getBrightness(){
        return jSliderBrightness.getValue();
    }
    
}
