/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Vicent Roig
 */
public class DialogEncode extends javax.swing.JDialog {
    private static int height;
    private static int width;
    private boolean confirm;
    private List brickSize;
    
    /**
     * Creates new form DialogEncode
     * @param parent
     * @param modal
     * @param w
     * @param h
     */
    public DialogEncode(java.awt.Frame parent, boolean modal, int w, int h) {
        super(parent, modal);
        this.height = w;
        this.width = h;
        this.brickSize = commonFactors(this.width,this.height);
        initComponents();
        this.confirm = false;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelQuality = new javax.swing.JPanel();
        jSliderQuality = new javax.swing.JSlider();
        jPanelParameters = new javax.swing.JPanel();
        jSpinnerPatchSize = new javax.swing.JSpinner();
        jSpinnerOffset = new javax.swing.JSpinner();
        jSpinnerGop = new javax.swing.JSpinner();
        jLabelPatchSize = new javax.swing.JLabel();
        jLabelOffset = new javax.swing.JLabel();
        jLabelGop = new javax.swing.JLabel();
        jLabelQuality = new javax.swing.JLabel();
        jButtonAccept = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compression configuration");
        setModal(true);
        setName("compression_conf"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanelQuality.setBorder(javax.swing.BorderFactory.createTitledBorder("Quality"));

        jSliderQuality.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jSliderQuality.setMajorTickSpacing(5);
        jSliderQuality.setMaximum(50);
        jSliderQuality.setMinimum(5);
        jSliderQuality.setMinorTickSpacing(1);
        jSliderQuality.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderQuality.setPaintLabels(true);
        jSliderQuality.setPaintTicks(true);
        jSliderQuality.setSnapToTicks(true);
        jSliderQuality.setValue(20);
        jSliderQuality.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jSliderQuality.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderQuality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderQualityMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelQualityLayout = new javax.swing.GroupLayout(jPanelQuality);
        jPanelQuality.setLayout(jPanelQualityLayout);
        jPanelQualityLayout.setHorizontalGroup(
            jPanelQualityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderQuality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );
        jPanelQualityLayout.setVerticalGroup(
            jPanelQualityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderQuality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanelParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        jPanelParameters.setName("Parameters"); // NOI18N

        jSpinnerPatchSize.setModel(new javax.swing.SpinnerListModel(this.brickSize));
        jSpinnerPatchSize.setValue(this.brickSize.get(4));
        jSpinnerPatchSize.setName(""); // NOI18N

        jSpinnerOffset.setModel(new javax.swing.SpinnerNumberModel(1, 0, 16, 1));
        jSpinnerOffset.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerOffset, ""));

        jSpinnerGop.setModel(new javax.swing.SpinnerNumberModel(10, 2, 15, 1));
        jSpinnerGop.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerGop, ""));

        jLabelPatchSize.setText("Patch size");

        jLabelOffset.setText("Offset");

        jLabelGop.setText("GOP");

        jLabelQuality.setText("Quality set to \t" + (float) (this.jSliderQuality.getValue()/1000.0));
        jLabelQuality.setToolTipText("");

        javax.swing.GroupLayout jPanelParametersLayout = new javax.swing.GroupLayout(jPanelParameters);
        jPanelParameters.setLayout(jPanelParametersLayout);
        jPanelParametersLayout.setHorizontalGroup(
            jPanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelParametersLayout.createSequentialGroup()
                        .addComponent(jLabelOffset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelParametersLayout.createSequentialGroup()
                        .addComponent(jLabelGop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerGop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelParametersLayout.createSequentialGroup()
                        .addComponent(jLabelQuality)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelParametersLayout.createSequentialGroup()
                        .addComponent(jLabelPatchSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerPatchSize, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelParametersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelGop, jLabelOffset, jLabelPatchSize, jSpinnerGop, jSpinnerOffset});

        jPanelParametersLayout.setVerticalGroup(
            jPanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametersLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPatchSize)
                    .addComponent(jSpinnerPatchSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOffset))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerGop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabelQuality)
                .addGap(25, 25, 25))
        );

        jButtonAccept.setText("Encode");
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelParameters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAccept, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelQuality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAccept)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Quality value setter
     * @param evt 
     */
    private void jSliderQualityMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderQualityMouseReleased
        //this.hue = jSliderHue.getValue();
        this.jLabelQuality.setText("Quality set to \t" + (float) (this.jSliderQuality.getValue()/1000.0));
    }//GEN-LAST:event_jSliderQualityMouseReleased

    
    /**
     * Accept button Action Listener. Accepts  hte set values and closes the dialog.
     * @param evt 
     */
    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        // TODO add your handling code here:
        confirm = true;
        this.dispose();
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    /**
     * Cancel button Listener. Closes the dialog.
     * @param evt 
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEncode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEncode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEncode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEncode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DialogEncode().setVisible(true);
                DialogEncode dialog = new DialogEncode(new javax.swing.JFrame(), true, width, height);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
     * Gets the quality value set by user on the slider
     * @return Quality.
     */
    public float getQuality(){
        return (float) (this.jSliderQuality.getValue()/1000.0);
    }
    
    /**
     * Gets the GOP value set by user on  the spinner. 
     * @return GOP value.
     */
    public int getGOP(){
       return (int) this.jSpinnerGop.getValue();
    }
    
    /**
     * Gets the offset value set by user on the spinner.
     * @return Offset value
     */
    public int getOffset(){
        return (int) this.jSpinnerOffset.getValue();
    }

    
    /**
     * Gets the patch size value set by user  on spinner
     * @return 
     */
    public int getPatchSize(){
      return (int) this.jSpinnerPatchSize.getValue();
    }

    
     /**
     * Returns the state of acceptance of the values in the dialog
     * @return True if values are accepted. False otherwise.
     */
    public boolean isAccepted(){
        return confirm;
    }
    
    /**
     * Method that calculates all the common divisors of two integers
     * @param p First Integer
     * @param q Second Integer
     * @return A list with all the common divisors of p and q
     */
    private List commonFactors(int p, int q){
        List result = new ArrayList<>();

        if(q > p){
            for(int i = 1;i < q;i++) if((q%i==0)&&(p%i==0)) result.add(i);
        }else {
            for(int i = 1;i < p;i++) if((p%i==0)&&(q%i==0)) result.add(i);
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabelGop;
    private javax.swing.JLabel jLabelOffset;
    private javax.swing.JLabel jLabelPatchSize;
    private javax.swing.JLabel jLabelQuality;
    private javax.swing.JPanel jPanelParameters;
    private javax.swing.JPanel jPanelQuality;
    private javax.swing.JSlider jSliderQuality;
    private javax.swing.JSpinner jSpinnerGop;
    private javax.swing.JSpinner jSpinnerOffset;
    private javax.swing.JSpinner jSpinnerPatchSize;
    // End of variables declaration//GEN-END:variables
}
